version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.4-jdk-stretch-node-browsers
      - image: circleci/redis
    environment:
      PORT: 8080
      SESSION_SECRET: notsosecret
      BIN_DIR: ./bin
      CLAIMANT_SERVICE_URL: http://localhost:8090
      USE_UNSECURE_COOKIE: true
      WEB_UI_BRANCH: 'feature/number-of-addresses' # if empty, download & run the latest release of web-ui. If populated, download & run that branch
      OS_PLACES_API_KEY: os-places-key
      OS_PLACES_URI: http://localhost:8150
    steps:
      - checkout
      - run:
          name: start chrome
          command: google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
      - restore_cache:
          key: v1-gradle-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - add_ssh_keys:
          fingerprints:
            - "81:ca:95:90:1b:25:e9:cb:e7:0c:89:41:b8:cf:7f:a0"
      - run:
          name: prepare for tests and build
          command: |
            export WEB_UI_DIR=$(pwd)/tmp-web-ui
            ./ci_scripts/prepare_for_tests.sh
            ./ci_scripts/download_chromedriver.sh
            ./run_tests_with_local_feature_toggles.sh
      - run:
          name: cat the RunAcceptanceTests logs for debugging on failure
          command: cat /home/circleci/project/build/reports/tests/test/classes/uk.gov.dhsc.htbhf.RunAcceptanceTests.html
          when: on_fail
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-gradle-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          when: always
      - persist_to_workspace:
          root: .
          paths:
            - ./*

  deploy:
    docker:
      - image: circleci/openjdk:11.0.4-jdk-stretch
    environment:
      BIN_DIR: ./bin
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "81:ca:95:90:1b:25:e9:cb:e7:0c:89:41:b8:cf:7f:a0"
      - attach_workspace:
          at: .
      - run:
          name: release
          command: ./ci_scripts/tag_version.sh

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
